#!/usr/bin/env php
<?php declare(strict_types=1);

use function Testimony\testify;

foreach ([
  dirname(__DIR__, 4) . DIRECTORY_SEPARATOR . 'composer.json',
  dirname(__DIR__) . DIRECTORY_SEPARATOR . 'composer.json'
] as $config_file) {
    if (is_file($config_file)) {
        define('TESTIMONY_ROOT', dirname($config_file) . DIRECTORY_SEPARATOR);
        break;
    }
}
unset($config_file);

if (!defined('TESTIMONY_ROOT')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can add the Testimony dependency correctly with:' . PHP_EOL . PHP_EOL .
        '    composer require testimony/testify' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    exit(1);
}

define('COMPOSER_FILE', TESTIMONY_ROOT . 'composer.json');

if(!in_array(php_sapi_name(), ['cli', 'phpdbg'])) {
  fprintf(
    STDERR,
    'Please run %s from CLI' . PHP_EOL,
    __FILE__
  );
  exit(1);
}

$composer_data = json_decode(file_get_contents(COMPOSER_FILE), true);
if (json_last_error()) {
  fprintf(
    STDERR,
    json_last_error_msg() . ' in %s' . PHP_EOL,
    COMPOSER_FILE
  );
  exit(1);
}

$autoload_file = TESTIMONY_ROOT . str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $composer_data['config']['vendor-dir'] ?? 'vendor') . DIRECTORY_SEPARATOR . 'autoload.php';
if(!is_file($autoload_file)) {
  fprintf(
    STDERR,
    'You must set the autoload file at %s' . PHP_EOL,
    $autoload_file
  );
  exit(1);
}

require_once $autoload_file;
unset($composer_data, $autoload_file);

testify($argc, $argv);